(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Colored Scalar + SM EFT",
  Authors -> {"Eliel Camargo-molina"},
  Version -> "1.0",
  Date -> "09.11.2023"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], sd -> S[4]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}, {NPcHG, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {-1/3*Y},
    Mass -> msd,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "sd" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ S[4] ] = GaugeXi[S[100]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
msd[ ___ ] := msd;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ S[4, {__}] ] := TheLabel[S[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, (I*(2*aEWM1*cHG*MW^4 - 2*aEWM1*cHG*MW^2*MZ^2 + MZ^2*Pi)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2])/(MZ^2*Pi)}, {0, 0}, {0, ((-I)*(2*aEWM1*cHG*MW^4 - 2*aEWM1*cHG*MW^2*MZ^2 + MZ^2*Pi)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2])/(MZ^2*Pi)}},

C[ S[2] , S[2] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(4*I)*cHG*IndexDelta[e1x2, e2x2]*(FV[3, List]*FV[4, List] - SP[3, 4]), (4*I)*cHG*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]*(FV[3, List]*FV[4, List] - SP[3, 4])}},

C[ S[3] , -S[3] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(4*I)*cHG*IndexDelta[e1x2, e2x2]*(FV[3, List]*FV[4, List] - SP[3, 4]), (4*I)*cHG*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]*(FV[3, List]*FV[4, List] - SP[3, 4])}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(4*I)*cHG*IndexDelta[e1x2, e2x2]*(FV[3, List]*FV[4, List] - SP[3, 4]), (4*I)*cHG*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]*(FV[3, List]*FV[4, List] - SP[3, 4])}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(4*I)*cHG*vev*IndexDelta[e1x2, e2x2]*(FV[2, List]*FV[3, List] - SP[2, 3]), (4*I)*cHG*vev*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]*(FV[2, List]*FV[3, List] - SP[2, 3])}},

C[ S[4, {e1x1}] , -S[4, {e2x1}] ] == {{0, (-I)*FR$deltaZ[{sd, sd}, {{}}]*IndexDelta[e1x1, e2x1]}, {0, ((-1/2*I)*(4*msd*MZ^2*Pi*FR$delta[{msd}, {}] + aEWM1*MW^4*FR$deltaZ[{sd, sd}, {{}}] - aEWM1*MW^2*MZ^2*FR$deltaZ[{sd, sd}, {{}}] + 2*msd^2*MZ^2*Pi*FR$deltaZ[{sd, sd}, {{}}])*IndexDelta[e1x1, e2x1])/(MZ^2*Pi)}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc9*SUNF[e3x2, e1x1, e2x1], -1/2*(GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/aS}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc11*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {(-I)*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc12*IndexDelta[e1x2, e2x2], ((-1/2*I)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc12*IndexDelta[e1x2, e2x2], ((-1/2*I)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc13*IndexDelta[e1x2, e2x2], ((-1/2*I)*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}, {I*gc13*IndexDelta[e1x2, e2x2], ((-1/2*I)*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc14*IndexDelta[e1x2, e2x2], ((-1/2*I)*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}, {I*gc14*IndexDelta[e1x2, e2x2], ((-1/2*I)*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc18, 0}, {I*gc18, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc19, 0}, {I*gc19, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc20, 0}, {I*gc20, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc21*IndexDelta[e1x2, e2x2], ((-1/2*I)*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}, {I*gc21*IndexDelta[e1x2, e2x2], ((-1/2*I)*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc22*IndexDelta[e1x2, e2x2], ((-1/2*I)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc22*IndexDelta[e1x2, e2x2], ((-1/2*I)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc23*IndexDelta[e1x2, e2x2], ((-1/2*I)*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}, {I*gc23*IndexDelta[e1x2, e2x2], ((-1/2*I)*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ S[4, {e2x1}] , -S[4, {e3x1}] , V[1] ] == {{(-1/3*I)*EL*IndexDelta[e2x1, e3x1], (-1/3*I)*EL*FR$deltaZ[{sd, sd}, {{}}]*IndexDelta[e2x1, e3x1]}},

C[ S[1] , S[1] , S[4, {e3x1}] , -S[4, {e4x1}] ] == {{I*lamsdh*IndexDelta[e3x1, e4x1], 0}},

C[ S[1] , S[4, {e2x1}] , -S[4, {e3x1}] ] == {{I*lamsdh*vev*IndexDelta[e2x1, e3x1], I*lamsdh*vev*FR$deltaZ[{sd, sd}, {{}}]*IndexDelta[e2x1, e3x1]}},

C[ S[4, {e3x1}] , -S[4, {e4x1}] , V[1] , V[1] ] == {{((2*I)/9)*EL^2*IndexDelta[e3x1, e4x1], ((2*I)/9)*EL^2*FR$deltaZ[{sd, sd}, {{}}]*IndexDelta[e3x1, e4x1]}},

C[ S[4, {e1x1}] , S[4, {e2x1}] , -S[4, {e3x1}] , -S[4, {e4x1}] ] == {{(2*I)*lamsd*(IndexDelta[e1x1, e4x1]*IndexDelta[e2x1, e3x1] + IndexDelta[e1x1, e3x1]*IndexDelta[e2x1, e4x1]), 0}},

C[ S[4, {e2x1}] , -S[4, {e3x1}] , V[4, {e1x2}] ] == {{I*GS*SUNT[e1x2, e3x1, e2x1], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{sd, sd}, {{}}])*SUNT[e1x2, e3x1, e2x1])/aS}},

C[ S[4, {e3x1}] , -S[4, {e4x1}] , V[1] , V[4, {e2x2}] ] == {{((-2*I)/3)*EL*GS*SUNT[e2x2, e4x1, e3x1], ((-1/3*I)*EL*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{sd, sd}, {{}}])*SUNT[e2x2, e4x1, e3x1])/aS}},

C[ S[4, {e3x1}] , -S[4, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), (I*GS^2*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + aS*FR$deltaZ[{sd, sd}, {{}}])*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]))/aS}},

C[ V[1] , V[3] , -V[3] ] == {{I*EL, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-2*I)*gc38, 0}, {I*gc38, 0}, {I*gc38, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-2*I)*gc40, 0}, {I*gc40, 0}, {I*gc40, 0}},

C[ S[4, {e1x1}] , -S[4, {e2x1}] , V[2] ] == {{((I/3)*EL*sw*IndexDelta[e1x1, e2x1])/cw, ((I/3)*EL*sw*FR$deltaZ[{sd, sd}, {{}}]*IndexDelta[e1x1, e2x1])/cw}},

C[ S[4, {e2x1}] , -S[4, {e3x1}] , V[1] , V[2] ] == {{(((-2*I)/9)*EL^2*sw*IndexDelta[e2x1, e3x1])/cw, (((-2*I)/9)*EL^2*sw*FR$deltaZ[{sd, sd}, {{}}]*IndexDelta[e2x1, e3x1])/cw}},

C[ S[4, {e2x1}] , -S[4, {e3x1}] , V[4, {e1x2}] , V[2] ] == {{(((2*I)/3)*EL*GS*sw*SUNT[e1x2, e3x1, e2x1])/cw, ((I/3)*EL*GS*sw*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{sd, sd}, {{}}])*SUNT[e1x2, e3x1, e2x1])/(aS*cw)}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc44, 0}, {(-I)*gc44, 0}, {(2*I)*gc44, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[4, {e1x1}] , -S[4, {e2x1}] , V[2] , V[2] ] == {{(((2*I)/9)*EL^2*sw^2*IndexDelta[e1x1, e2x1])/cw^2, (((2*I)/9)*EL^2*sw^2*FR$deltaZ[{sd, sd}, {{}}]*IndexDelta[e1x1, e2x1])/cw^2}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-2*I)*gc48, 0}, {I*gc48, 0}, {I*gc48, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc49, 0}, {I*gc49, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc50, 0}, {I*gc50, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc51, 0}, {I*gc51, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc52*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc52*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc53*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc53*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc54*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc54*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc55*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc55*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc56*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc56*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc57*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc57*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc58*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc58*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc59*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc59*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc60*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc60*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc61*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc61*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc62*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc62*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc63*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc63*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc64*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x1*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc65*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x2*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc66*IndexDelta[e1x2, e2x2], ((I/2)*CKM3x3*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc67*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x1*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc68*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x2*EL*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc69*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM3x3]*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc70*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x1]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc71*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x1]*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc72*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x2]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc73*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x2]*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc74, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc75, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc76, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc77, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc78, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc79, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc80L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc80R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc81L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc81R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc82L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc82R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc83L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc83R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc84L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc84R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc85L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc85R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc86, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc87, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc88, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc89L, 0}, {I*gc89R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc90L, 0}, {I*gc90R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc91L, 0}, {I*gc91R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc9 -> -GS,
     gc11 -> GS^2,
     gc12 -> -(yb/Sqrt[2]),
     gc13 -> -(ydo/Sqrt[2]),
     gc14 -> -(ys/Sqrt[2]),
     gc18 -> -(ye/Sqrt[2]),
     gc19 -> -(ym/Sqrt[2]),
     gc20 -> -(ytau/Sqrt[2]),
     gc21 -> -(yc/Sqrt[2]),
     gc22 -> -(yt/Sqrt[2]),
     gc23 -> -(yup/Sqrt[2]),
     gc38 -> EL^2,
     gc40 -> -(EL^2/sw^2),
     gc44 -> -((cw*EL^2)/sw),
     gc48 -> (cw^2*EL^2)/sw^2,
     gc49 -> -EL,
     gc50 -> -EL,
     gc51 -> -EL,
     gc52 -> (2*EL)/3,
     gc53 -> (2*EL)/3,
     gc54 -> (2*EL)/3,
     gc55 -> -1/3*EL,
     gc56 -> -1/3*EL,
     gc57 -> -1/3*EL,
     gc58 -> GS,
     gc59 -> GS,
     gc60 -> GS,
     gc61 -> GS,
     gc62 -> GS,
     gc63 -> GS,
     gc64 -> (CKM2x1*EL)/(Sqrt[2]*sw),
     gc65 -> (CKM2x2*EL)/(Sqrt[2]*sw),
     gc66 -> (CKM3x3*EL)/(Sqrt[2]*sw),
     gc67 -> (CKM1x1*EL)/(Sqrt[2]*sw),
     gc68 -> (CKM1x2*EL)/(Sqrt[2]*sw),
     gc69 -> (EL*Conjugate[CKM3x3])/(Sqrt[2]*sw),
     gc70 -> (EL*Conjugate[CKM2x1])/(Sqrt[2]*sw),
     gc71 -> (EL*Conjugate[CKM1x1])/(Sqrt[2]*sw),
     gc72 -> (EL*Conjugate[CKM2x2])/(Sqrt[2]*sw),
     gc73 -> (EL*Conjugate[CKM1x2])/(Sqrt[2]*sw),
     gc74 -> EL/(Sqrt[2]*sw),
     gc75 -> EL/(Sqrt[2]*sw),
     gc76 -> EL/(Sqrt[2]*sw),
     gc77 -> EL/(Sqrt[2]*sw),
     gc78 -> EL/(Sqrt[2]*sw),
     gc79 -> EL/(Sqrt[2]*sw),
     gc80L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc80R -> (-2*EL*sw)/(3*cw),
     gc81L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc81R -> (-2*EL*sw)/(3*cw),
     gc82L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc82R -> (-2*EL*sw)/(3*cw),
     gc83L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc83R -> (EL*sw)/(3*cw),
     gc84L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc84R -> (EL*sw)/(3*cw),
     gc85L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc85R -> (EL*sw)/(3*cw),
     gc86 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc87 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc88 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc89L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc89R -> (EL*sw)/cw,
     gc90L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc90R -> (EL*sw)/cw,
     gc91L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc91R -> (EL*sw)/cw};

